spring:
    datasource:
        driver-class-firstName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/foodliverydb
        username: root
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    main:
        allow-circular-references: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: lucadevelopertest@gmail.com
        password: WuVbuV-Z:rdbJ2Q
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
